language: python

python:
  - "2.7"
  - "3.5"

matrix:
  include:
    - python: "2.7"
      env: TEST_SUITE=py27
    - python: "3.5"
      env: TEST_SUITE=py35

install:
  - pip install tox

# command to run tests
script:
  - tox -e pycodestyle
  - tox -e $TEST_SUITE
