language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"

matrix:
  include:
    - python: "2.6"
      env: TEST_SUITE=py26
    - python: "2.7"
      env: TEST_SUITE=py27
    - python: "3.4"
      env: TEST_SUITE=py34

install:
  - pip install tox

# command to run tests
script:
  - tox -e pycodestyle
  - tox -e $TEST_SUITE
